name: homedevices-oop-servlet-jsp-jdbc

services:
  database:
    container_name: homedevices-jdbc
    image: postgres:17.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
